# Generated by Django 5.2.5 on 2025-08-26 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('sqlite', 'SQLite')], max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('database_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Database Connection',
                'verbose_name_plural': 'Database Connections',
            },
        ),
        migrations.CreateModel(
            name='DatabaseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_queries', models.IntegerField(default=0)),
                ('successful_queries', models.IntegerField(default=0)),
                ('failed_queries', models.IntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('database_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.databaseconnection')),
            ],
            options={
                'verbose_name': 'Database Statistics',
                'verbose_name_plural': 'Database Statistics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_timeout', models.IntegerField(default=8, help_text='Query timeout in seconds')),
                ('monitoring_interval', models.IntegerField(default=300, help_text='Monitoring interval in seconds')),
                ('email_recipients', models.TextField(help_text='Comma-separated email addresses')),
                ('alert_threshold', models.IntegerField(default=1000, help_text='Alert when query count exceeds this')),
                ('is_monitoring_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.databaseconnection')),
            ],
            options={
                'verbose_name': 'Monitoring Configuration',
                'verbose_name_plural': 'Monitoring Configurations',
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], max_length=20)),
                ('execution_time', models.FloatField(help_text='Execution time in seconds')),
                ('result_count', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('database_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.databaseconnection')),
            ],
            options={
                'verbose_name': 'Query Log',
                'verbose_name_plural': 'Query Logs',
                'ordering': ['-executed_at'],
            },
        ),
    ]
