# Generated by Django 5.2.5 on 2025-08-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('query', models.TextField()),
                ('interval', models.PositiveIntegerField(help_text='Interval in seconds')),
                ('format', models.CharField(choices=[('excel', 'Excel (.xlsx)'), ('csv', 'CSV (.csv)')], default='excel', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
