# Generated by Django 5.2.5 on 2025-09-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0003_reportlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportLog',
        ),
        migrations.DeleteModel(
            name='ReportSchedule',
        ),
    ]
