# Generated by Django 5.2.6 on 2025-09-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docusense", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("docx", "Word Document"),
                    ("txt", "Text File"),
                    ("xlsx", "Excel File"),
                ],
                max_length=10,
            ),
        ),
    ]
