# Generated by Django 5.2.6 on 2025-09-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docusense", "0002_alter_document_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("docx", "Word Document"),
                    ("txt", "Text File"),
                    ("xlsx", "Excel File"),
                    ("xls", "Excel File (Old Format)"),
                ],
                max_length=10,
            ),
        ),
    ]
