# Generated by Django 4.2.7 on 2025-09-01 04:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('total_regions_found', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NumberRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropped_image', models.ImageField(upload_to='number_regions/')),
                ('region_index', models.IntegerField()),
                ('bbox_x', models.IntegerField()),
                ('bbox_y', models.IntegerField()),
                ('bbox_width', models.IntegerField()),
                ('bbox_height', models.IntegerField()),
                ('confidence_score', models.FloatField()),
                ('extracted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_regions', to='extractor.uploadedimage')),
            ],
            options={
                'ordering': ['parent_image', 'region_index'],
            },
        ),
    ]
